easy_admin:
    site_name: 'Chapi Time'
    list:
        max_results: 30
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y'
    entities:
        UsuarioTrabajador:
            disabled_actions: ['new']
            class: UserBundle\Entity\UsuarioTrabajador
            list:
                fields: ['nombre','apellidos','username','email', 'datosPrestaciones','puestos','enabled','lastLogin','roles']
            new:
                fields: ['nombre','apellidos',,'username','email','datosPrestaciones','puestos','enabled','password','roles']
        Actividad:
            class: AppBundle\Entity\Actividad
        Cliente:
            class: AppBundle\Entity\Cliente
        RegistroHoras:
            class: AppBundle\Entity\RegistroHoras
            list:
                fields: ['id','fechaHoras','horasInvertidas','actividad', 'cliente','ingresadoPor','proyectoPresupuesto']
            new:
                fields: ['id','fechaHoras','horasInvertidas','actividad', 'cliente','ingresadoPor','proyectoPresupuesto']
            edit:
                fields: ['id','fechaHoras','horasInvertidas','actividad', 'cliente','ingresadoPor','proyectoPresupuesto']
        RegistroHorasPresupuesto:
            disabled_actions: ['edit', 'delete']
            class: AppBundle\Entity\RegistroHorasPresupuesto
        ProyectoPresupuesto:
            disabled_actions: ['edit', 'delete']
            class: AppBundle\Entity\ProyectoPresupuesto
        Costo:
            class: CostoBundle\Entity\Costo
        Codigo:
            class: UserBundle\Entity\Codigo
        Departamento:
            class: UserBundle\Entity\Departamento
        TipoPuesto:
            class: UserBundle\Entity\TipoPuesto
        Puesto:
            class: UserBundle\Entity\Puesto
