fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\Usuario
    service:
        user_manager: pugx_user_manager

pugx_multi_user:
  users:
    user_one:
        entity: 
          class: UserBundle\Entity\UsuarioTrabajador
#          factory: 
        registration:
          form: 
            type: UserBundle\Form\Type\RegistrationTrabajadorFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: UserBundle:Registration:register.html.twig
        profile:
          form:
            type: UserBundle\Form\Type\ProfileTrabajadorFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default] 
    user_two:
        entity: 
          class: UserBundle\Entity\UsuarioSocio
        registration:
          form: 
            type: UserBundle\Form\Type\RegistrationSocioFormType
          template: UserBundle:Registration:register_socio.html.twig
        profile:
          form: 
            type: UserBundle\Form\Type\ProfileSocioFormType