fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\Usuario
    registration:
          confirmation:
            from_email:
                address:        no-responder@newtonlabs.com.gt
                sender_name:    Smart Time
            enabled:    false # change to true for required email confirmation
            template:   UserBundle:Registration:registration.email.twig  
    resetting: #password resetting
        token_ttl: 86400
        email:
            from_email:
                address:        no-responder@newtonlabs.com.gt
                sender_name:    Smart Time
            template:   UserBundle:Resetting:resetting.email.twig
    service:
        user_manager: pugx_user_manager
        mailer: fos_mail.custom_mailer

pugx_multi_user:
  users:
    user_one:
        entity: 
          class: UserBundle\Entity\UsuarioTrabajador
#          factory: 
        registration:
          form: 
            type: UserBundle\Form\Type\RegistrationTrabajadorFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default, EmailDomainValidation]
          template: UserBundle:Registration:register.html.twig
        profile:
          form:
            type: UserBundle\Form\Type\ProfileTrabajadorFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default] 
    user_two:
        entity: 
          class: UserBundle\Entity\UsuarioSocio
        registration:
          form: 
            type: UserBundle\Form\Type\RegistrationSocioFormType
            validation_groups:  [Registration, Default]
          template: UserBundle:Registration:register_socio.html.twig
        profile:
          form: 
            type: UserBundle\Form\Type\ProfileSocioFormType
