knp_gaufrette:
    stream_wrapper: ~

    adapters:
        product_adapter:
            local:
                directory: "%kernel.root_dir%/../web/docs"
        foo:
            aws_s3:
                service_id: 'acme.aws_s3.client'
                bucket_name: 'smart-time'
                options:
                    directory: 'user-images'

    filesystems:
        archivos:
            adapter:    foo
