security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                login_path: /
                check_path: /check
            logout:       true
            anonymous:    true
            access_denied_url: /
            guard:
                authenticators:
                    - app.token_authenticator
            #access_denied_handler: kernel.listener.accessDenied
            #entry_point: kernel.listener.accessDenied
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/puesto/, roles: ROLE_USER }
        - { path: ^/actividad/, roles: ROLE_USER }
        - { path: ^/registrohoras/, roles: ROLE_USER }
        - { path: ^/cliente/, roles: ROLE_USER }
        - { path: ^/datosprestaciones/, roles: ROLE_USER }
        - { path: ^/admin/, roles: [ ROLE_GERENTE, ROLE_SOCIO] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }



    role_hierarchy:
        ROLE_ASISTENTE:         ROLE_USER
        ROLE_ENCARGADO:         ROLE_ASISTENTE
        ROLE_SUPERVISOR:        ROLE_ENCARGADO
        ROLE_GERENTE:           ROLE_SUPERVISOR
        ROLE_SOCIO:             ROLE_GERENTE
        ROLE_ADMIN:             ROLE_SOCIO
        ROLE_SUPER_ADMIN:       ROLE_ADMIN
