security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                login_path: /login
                check_path: /check
            remember_me:
                key: "%secret%"
                path:     /
                always_remember_me: true
            logout:
                path: /logout
                target: /api/logout
                invalidate_session: true
            anonymous:    true
            access_denied_url: /forbidden
            guard:
                authenticators:
                    - app.token_authenticator
            #access_denied_handler: kernel.listener.accessDenied
            #entry_point: kernel.listener.accessDenied
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forbidden, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ] }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/trabajador, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/costo/calcular/todos, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/costo/calcular/view, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/puesto/, roles: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ] }
        - { path: ^/actividad/, roles: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ] }
        - { path: ^/registrohoras/, roles: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ] }
        - { path: ^/cliente/, roles: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ] }
        - { path: ^/datosprestaciones/, roles: [IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ] }
        - { path: ^/admin/, roles: [ROLE_ADMIN] }
        



    role_hierarchy:
        #permiso para aprobar automáticamente las horas
        ROLE_APROBACION_HORAS_AUTOMATICO: ROLE_USER
        #permiso para que otros usuarios se asignen en un presupuesto
        ROLE_ASIGNACION: ROLE_USER
        #Permiso para ver el listado general de horas
        ROLE_VER_LISTADO_GENERAL: ROLE_USER
        #permiso para ver listado general de actividades
        ROLE_VER_ACTIVIDADES: ROLE_USER
        #permiso para ver listado general de presupuestos
        ROLE_VER_PRESUPUESTOS: ROLE_USER
        #Permiso para aprobar de horas
        ROLE_APROBACION_HORAS: ROLE_USER
        #Permiso para ver clientes
        ROLE_VER_CLIENTES: ROLE_USER
        #permiso para ver consultas de costos
        ROLE_VER_CONSULTAS: ROLE_USER
        #permiso para ver los tipos de puestos
        ROLE_VER_PUESTO_Y_TIPO: ROLE_USER
        #permiso para ver los departamentos
        ROLE_VER_DEPARTAMENTO: ROLE_USER
        #permiso para crear clientes
        ROLE_CREAR_CLIENTES: ROLE_VER_CLIENTES
        #permiso para crear actividades
        ROLE_CREAR_ACTIVIDADES: ROLE_VER_ACTIVIDADES
        #permiso para crear horas
        ROLE_CREAR_HORAS: ROLE_VER_LISTADO_GENERAL
        #permiso para crear preseupuesto
        ROLE_CREAR_PRESUPUESTOS: ROLE_VER_PRESUPUESTOS
        #permiso para crear usuarios
        ROLE_GESTIONAR_USUARIOS: ROLE_USER
        #permiso para crear tipo puesto
        ROLE_CREAR_PUESTO_Y_TIPO: ROLE_VER_PUESTO_Y_TIPO
        #permiso para crear departamentos
        ROLE_CREAR_DEPARTAMENTO: ROLE_VER_DEPARTAMENTO
        #permiso para editar horas
        ROLE_EDITAR_HORAS: ROLE_CREAR_HORAS
        #permiso para editar atividades
        ROLE_EDITAR_ACTIVIDADES: ROLE_CREAR_ACTIVIDADES
        #permiso para editar presupuestos
        ROLE_EDITAR_PRESUPUESTO: ROLE_CREAR_PRESUPUESTOS
        #permiso para editar clientes
        ROLE_EDITAR_CLIENTES: ROLE_CREAR_CLIENTES
        #permiso para editar tipo puesto
        ROLE_EDITAR_PUESTO_Y_TIPO: ROLE_CREAR_PUESTO_Y_TIPO
        #permiso para editar departamentos
        ROLE_EDITAR_DEPARTAMENTO: ROLE_CREAR_DEPARTAMENTO
        #permiso para eliminar horas
        ROLE_ELIMINAR_HORAS: ROLE_EDITAR_HORAS
        #permiso para eliminar presupuestos
        ROLE_ELIMINAR_PRESUPUESTOS: ROLE_EDITAR_PRESUPUESTO
        #permiso para eliminar actividades
        ROLE_ELIMINAR_ACTIVIDADES: ROLE_EDITAR_ACTIVIDADES
        #permisio para eliminear clientes
        ROLE_ELIMINAR_CLIENTES: ROLE_EDITAR_CLIENTES
        #permiso para eliminar tipo puestos
        ROLE_ELIMINAR_PUESTO_Y_TIPO: ROLE_EDITAR_PUESTO_Y_TIPO
        #permiso para eliminar departamentos
        ROLE_ELIMINAR_DEPARTAMENTO: ROLE_EDITAR_DEPARTAMENTO
        #permiso para tener acceso al panel de control.
        ROLE_ADMIN:             
            - ROLE_ELIMINAR_CLIENTES
            - ROLE_ELIMINAR_USUARIOS
            - ROLE_ELIMINAR_ACTIVIDADES
            - ROLE_ELIMINAR_HORAS
            - ROLE_ELIMINAR_PRESUPUESTOS
            - ROLE_VER_CONSULTAS
            - ROLE_APROBACION_HORAS
            - ROLE_ELIMINAR_PUESTO_Y_TIPO
            - ROLE_ELIMINAR_DEPARTAMENTO
            - ROLE_APROBACION_HORAS_AUTOMATICO
            - ROLE_ASIGNACION
            - ROLE_GESTIONAR_USUARIOS
        ROLE_SUPER_ADMIN:       ROLE_ADMIN
