# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: amazon.php }

parameters:
#    parameter_name: value

services:
    #    service_name:
    #        class: AppBundle\Directory\ClassName
    #        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    # entry_point.user_login:
    #    class: UserBundle\Service\LoginEntryPoint
    #    arguments: [ @router ] #I am going to use this for URL generation since I will be redirecting in my service
    app.token_authenticator:
        class: UserBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager','@service_container']

    app.twig_extension:
        class: CostoBundle\Twig\ArrayExtension
        public: false
        tags:
            - { name: twig.extension }
    consulta.query_controller:
        class: CostoBundle\Controller\QueryController
        calls:
        - [setContainer, ["@service_container"]]
    appstate:
        class: AppBundle\Extensions\HorasPendientes
        arguments: [@security.token_storage, @doctrine.orm.entity_manager]
    twig.extension.appstate:
        class: AppBundle\Extensions\HorasPendientesExtension
        arguments: [@appstate]
        tags:
            - { name: twig.extension }
    acme.aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                credentials: 
                    key:      "%aws_key%"
                    secret:   "%aws_secret_key%"                
                region:   "us-east-1"
                version:  "latest"
    gedmo.listener.blameable:
      class: UserBundle\Listener\BlameableListener
      tags:
        - { name: doctrine.event_subscriber, connection: default }
      calls:
        - [ setAnnotationReader, [ "@annotation_reader" ] ]
        - [ setUserValue, [ @security.token_storage ] ]
    app.datatable.registrohoras:
        class: AppBundle\Datatables\RegistroHorasDatatable
        parent: sg_datatables.datatable.abstract
    app.datatable.actividad:
        class: AppBundle\Datatables\ActividadDatatable
        parent: sg_datatables.datatable.abstract
