vich_uploader:
    db_driver: orm
    storage:   gaufrette
    mappings:
        user_imager:
            uri_prefix:         https://s3.amazonaws.com/smart-time/user-images
            upload_destination: archivos
            namer:              vich_uploader.namer_origname
            inject_on_load:     false
            delete_on_update:   true 
            delete_on_remove:   true
