<?php

namespace UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroHorasRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioTrabajadorRepository extends EntityRepository
{
    public function getQueryUsuariosPorTipoPuesto($arrayTipoPuestos)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('usuario')
            ->from('UserBundle:UsuarioTrabajador', 'usuario')
            ->leftjoin('usuario.puestos', 'puesto')
            ->leftjoin('puesto.tipopuesto', 'tipopuesto')
            ->where($qb->expr()->in(':tipopuesto'))
            ->setParameter('tipopuesto', $arrayTipoPuestos);

        return $qb->getQuery()->getResult();
    }
}
