user_homepage:
    path:     /hello/{name}
    defaults: { _controller: UserBundle:Default:index }

trabajador_registration:
    pattern:  /register/trabajador
    defaults: { _controller: UserBundle:RegisterTrabajador:register }

socio_registration:
    pattern:  /register/socio
    defaults: { _controller: UserBundle:RegisterSocio:register }
