user_homepage:
    path:     /hello/{name}
    defaults: { _controller: UserBundle:Default:index }

user_one_registration:
    pattern:  /register/user-one
    defaults: { _controller: UserBundle:Register:register }

user_two_registration:
    pattern:  /register/user-two
    defaults: { _controller: UserBundle:Register:register }
