user_homepage:
    path:     /hello/{name}
    defaults: { _controller: UserBundle:Default:index }

trabajador_registration:
    path:  /register/trabajador
    defaults: { _controller: UserBundle:RegisterTrabajador:register }

socio_registration:
    path:  /register/socio
    defaults: { _controller: UserBundle:RegisterSocio:register }

datos_prestaciones:
    resource: "@UserBundle/Controller/DatosPrestacionesController.php"
    type:     annotation

tipo_puesto:
    resource: "@UserBundle/Controller/TipoPuestoController.php"
    type:     annotation

codigo:
  resource: "@UserBundle/Controller/CodigoController.php"
  type: annotation

departamento:
    resource: "@UserBundle/Controller/DepartamentoController.php"
    type:     annotation

puesto:
   resource: "@UserBundle/Controller/PuestoController.php"
   type: annotation

combinar_puesto:
   resource: "@UserBundle/Controller/CombinarPuestoController.php"
   type: annotation

descuento:
  resource: "@UserBundle/Controller/DescuentoController.php"
  type: annotation

user_profile:
    path:  /edit/usuario
    defaults: { _controller: UserBundle:Profile:edit }

