<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CostoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadRepository extends EntityRepository
{
    public function findByRegistros($registros)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->select('a')
            ->innerJoin('AppBundle:RegistroHoras', 'r', 'with', 'r.actividad = a.id')
            ->where('r IN (:registros)')
            ->setParameter('registros', $registros);

        return $qb->getQuery()->getResult();
    }

    public function findByRegistrosPresupuesto($registros)
    {
        $idRegistros = $this->filterIds($registros);

        $qb = $this->createQueryBuilder('a');
        $qb
            ->select('a')
            ->innerJoin('AppBundle:Area', 'r', 'with', 'r.id = a.area')
            ->where('r.id IN (:registros)')
            ->setParameter('registros', $idRegistros);

        return $qb->getQuery()->getResult();
    }

    /**
     * Function to get the actividad ids of each register.
     *
     * @param RegistroPreupuesto $registros array
     *
     * @return array array of numbers
     */
    private function filterIds($registros)
    {
        $idRegistros = [];
        foreach ($registros as $registro) {
            $idRegistros[] = $registro->getArea()->getId();
        }

        return $idRegistros;
    }
}
