<?php

namespace AppBundle\Entity;

/**
 * AsignacionClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
