<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroHorasRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroHorasPresupuestoRepository extends EntityRepository
{
    public function findByCliente($proyecto, $cliente)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('registro')
            ->from('AppBundle:RegistroHorasPresupuesto', 'registro')
            ->where('registro.proyecto = :proyecto')
            ->andWhere('registro.cliente = :cliente')
            ->setParameter('proyecto', $proyecto)
            ->setParameter('cliente', $cliente)
            ;

        return $qb->getQuery()->getResult();
    }

    public function findByUsuario($proyecto, $usuario)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('registro')
            ->from('AppBundle:RegistroHorasPresupuesto', 'registro')
            ->where('registro.proyecto = :proyecto')
            ->leftJoin('registro.usuariosAsignados', 'usuario')
            ->andWhere('usuario = :usuario')
            ->setParameter('proyecto', $proyecto)
            ->setParameter('usuario', $usuario)
            ;

        return $qb->getQuery()->getResult();
    }
}
